name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Frontend CI
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Build
        run: npm run build --if-present
        working-directory: ./frontend
      - name: Test
        run: npm test
        working-directory: ./frontend

      - name: Backend CI
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./backend/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./backend
      - name: Build
        run: npm run build --if-present
        working-directory: ./backend
      - name: Test
        run: npm test
        working-directory: ./backend